# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/psf/black
      rev: 22.8.0
      hooks:
          - id: black
            args:
                - "--line-length=120"
    - repo: https://github.com/PyCQA/autoflake
      rev: v1.7.5
      hooks:
          - id: autoflake
            args:
                - "--in-place"
                - "--expand-star-imports"
                - "--remove-duplicate-keys"
                - "--remove-unused-variables"
                - "--remove-all-unused-imports"
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            name: isort (python)
            args: ["--profile", "black", "--filter-files"]

    - repo: https://github.com/pycqa/flake8
      rev: "5.0.4"
      hooks:
          - id: flake8
